import assert from 'node:assert/strict';
import { readFile, stat } from 'node:fs/promises';
const json = async (p) => JSON.parse(await readFile(p, 'utf8'));
const base = 'plugins/loom-memory';
const claude = await json(`${base}/.claude-plugin/plugin.json`);
const codex = await json(`${base}/.codex-plugin/plugin.json`);
assert.equal(claude.name, 'loom-memory'); assert.equal(codex.name, claude.name);
assert.equal(codex.version, claude.version);
const c = await json('.claude-plugin/marketplace.json');
const x = await json('.agents/plugins/marketplace.json');
assert.equal(c.name, 'loom-plugins'); assert.equal(x.name, c.name);
assert.equal(c.plugins[0].source, `./${base}`);
assert.equal(c.plugins[0].version, claude.version);
assert.equal(x.plugins[0].source.path, `./${base}`);
assert.equal(x.plugins[0].policy.installation, 'AVAILABLE');
assert.equal(x.plugins[0].policy.authentication, 'ON_INSTALL');
const mcp = await json(`${base}/.mcp.json`);
assert.equal(mcp.mcpServers.loom.url, 'https://api.neuradex.ai/mcp');
assert.equal(mcp.mcpServers.loom.type, 'http');
assert.equal(mcp.mcpServers['loom-memory'].args[0], '${CLAUDE_PLUGIN_ROOT}/dist/cli.js');
assert.equal((await json(`${base}/hooks/hooks.json`)).hooks.SessionEnd[0].hooks[0].timeout, 3);
for (const file of ['dist/cli.js','THIRD_PARTY_NOTICES.txt','skills/loom-memory/SKILL.md']) assert((await stat(`${base}/${file}`)).size > 0);
console.log('Both marketplace catalogs, package manifests and shipped runtime validated.');
